---
# Reference: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: false
contact_links:
  - name: ğŸ“– Contribution Guide
    url: https://github.com/AzorianSolutions/reflective/blob/main/docs/wiki/contributing/README.md
    about: "Please read through our contribution guide before opening an issue or pull request"
  - name: â“ Discussion
    url: https://github.com/AzorianSolutions/reflective/discussions
    about: "If you're just looking for help, try starting a discussion instead"
  - name: ğŸ’¬ Discord Server
    url: https://discord.azorian.solutions
    about: "Join our Discord server to discuss the project with other users and developers"